### ISSUE TITLE
Addition of cosine similarity and fc-a method.

### ISSUE THREAD

**Issue by r5sb** [queenie88/A-GCN#1]
Hello,

I hope you are doing well. Thank you for providing the code to your paper. I was wondering if the two other adjacency matrix building methods can be included in the models__adapt.py code. I had a doubt whether the cosine similarity is done by calculating torch.nn.CosineSimilarity() for each embedding pair. Only the code for the 1x1 conv method is provided in the models__adapt.py if I'm not wrong. I will really appreciate your help. Thank you!

**Comment by queenie88** [comment]
The repository only contains the code with the best performance of our method. And the other three alternative structures are not included. As you said in the question, we don’t use the cosine similarity function from PyTorch directly to compute the adjacent matrix. But it is still possible to do that by check about how to set the tensor to compute the cosine similarity before calling that function.
I hope this could be helpful.

**Comment by r5sb** [comment]
Thank you for your reply. I had another question about the FC layer dimensionality. From the paper my understanding is that it is dependant on the dataset. So for d=300 (Glove) and C = 80 (COCO), the dimensionality is 24000 X 1 ? How does it map to the 80 X 80 correlation matrix?  Please correct me if I am wrong. Thank you!
