### ISSUE TITLE
Unable to Run the Code on Colab

### ISSUE THREAD

**Issue by fakharunnisa95** [queenie88/A-GCN#2]
FileNotFoundError                         Traceback (most recent call last)
/content/A-GCN/demo_coco__adapt.py in <module>()
     78 
     79 if __name__ == '__main__':
---> 80     main_coco()

3 frames
/usr/lib/python3.6/os.py in makedirs(name, mode, exist_ok)
    218             return
    219     try:
--> 220         mkdir(name, mode)
    221     except OSError:
    222         # Cannot rely on checking for EEXIST, since the operating system

FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by queenie88** [comment]
The code is worked. Please check the path and download the dataset.

**Comment by queenie88** [comment]
Please, check out your configuration environment and code.
