### ISSUE TITLE
Question about gradient flow

### ISSUE THREAD

**Issue by rljahn** [queenie88/A-GCN#4]
Hi,  
I have a question about the implementation. See the following figure:
![image](https://user-images.githubusercontent.com/72928406/115887057-2185fe80-a484-11eb-9379-b8a1d24793d4.png)

If **adj** is **detached** from the computation graph, how could the two weight matrices be updated (i.e. **W_phi, W_theta**)?  Please let me know if I am wrong.

P.S. I haven't run ur code yet, but I run the following code to test the gradient flow. 
https://gist.github.com/rljahn/11ceccef6c85ace9b4d10115632b5582

**Comment by queenie88** [comment]
You are right，the .detech() should be removed. We forget to modify this code, but now we have updated it in our code. Thanks for pointing it out.
